server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smbms?Unicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: full
  type-aliases-package: cn.bdqn.demo.entity
  mapper-locations: classpath:mapper/*.xml
